---
title: "ms_2"
author: "Rachel Phan"
date: "2/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# URL For My Repo

https://github.com/rjphan/ms_2.git

# Projects

## Sanjana Ramrajvel: Homelessness in the U.S

The author of this website analyzed how effective homeless shelters were in matching the homeless population with availabile beds across the US. Some cons of the data analysis include unclear labeling of the axes. For example, for one chart called "Trends in the number of beds available for people experiencing homelessness from 2007-2018," the y-axis is labeled as "Total Year Round Beds (ES, TH, SH)", but ES, TH, and SH are not defined anywhere. In the "Overall" portion of the website, there is a graph of the total homeless population and beds available in the US, as well as individual states, but I would have liked to see a graph with all the states and their proportional homeless population and beds available so that I can easily compare them. Some pros of the data visualization was definitely the "Annual Percentage of Unsheltered Homeless Individuals" graph, which was coloured by state. The graph was very visually pleasing. However, again, the labelling of the x-axis was unclear and jumbled, so it was hard to read.

## Neil Khurana: Harvard Dining

The author of this website scraped the HUDS website to compile a list and analyze trends on the variety and frequency of dining hall options at Harvard. Some pros of the data analysis are that the graphs are very easy to read: you can clearly tell which options are served the most frequently. However, I would have liked the y-axis of the frequency graphs to be labeled with the units of frequency (# of times it has been served VS. number of days it was on?). It was also interesting that the author chose not only the frequency of times the entrees were served, but also what day of the week they were most served on. Some cons of the data analysis are that, aside from using this to know what days of the week certain entrees are served on and how often, there is not much else the data can tell you. It also measures the top 10 meat dishes, but it would have been interesting to see the trends of the popularity of the meat dishes compared to, say, the vegan options, and whether that ratio is porportionate to the number of Harvard students who are vegan. I think that would be more informative than a simple listing of the most popular dishes at HUDS.